 <div class="mt-5">
     <div class="row">

         <form action="/configurar" method="post">
             <h4 id="titulo" class="center">Adicionar horários</h4>
             <div>
                 <strong id="titulo">Nome</strong>
                 <input id='formulario' type="text" name="nome" class="form-control form-control-sm" value="<?= $this->view->medico['nome'] ?>">
             </div>

             <div class="mt-3">
                 <strong id="titulo">Data e hora</strong>
                 <input name="data_horario" id='formulario' type="datetime-local" class="form-control form-control-sm" placeholder="Escolha uma senha forte e segura">
             </div>

             <div class="center">
                 <button id="realizarCadastro" class="btn btn-sm">Adicionar horário</button>
             </div>
             <div id="linkColorInfo" class="mb-5">
                 <a href="/">Voltar para a Página Inicial</a>
             </div>


         </form>

         <span class="mx-5"></span>
         <div>
             <h4 id="titulo" class="center">Horários configurados</h4>
             <div id="horario" class="row">
                 <div>
                     <label for="">16/11/2020 07:00</label>
                 </div>
                 <div>
                     <a href="" id="remover">Remover</a>
                 </div>
             </div>

         </div>

     </div>
 </div>