<div class="mt-5">
    <form action="/cadastro" method="post">
        <h4 id="titulo" class="center">Cadastro de médico</h4>

        <div>
            <strong id="titulo">Nome</strong>
            <input name="nome" value="<?= $this->view->medico['nome'] ?>" id='formulario' type="text" class="form-control form-control-sm" placeholder="Insira o nome do profissional">
        </div>
        <div class="mt-3">
            <strong id="titulo">E-mail</strong>
            <input name="email" value="<?= $this->view->medico['email'] ?>" id='formulario' type="email" class="form-control form-control-sm" placeholder="exemplo@dominio.com.br">
        </div>
        <div class="mt-3">
            <strong id="titulo">Senha</strong>
            <input name="senha" value="<?= $this->view->medico['senha'] ?>" id='formulario' type="password" class="form-control form-control-sm" placeholder="Escolha uma senha forte e segura">
        </div>
        <?php if ($this->view->erroCadastro) { ?>
            <small class="center form-text text-danger">Erro ao tentar realizar o cadastro, verifique se os campos foram preenchidos corretamente.</small>
        <?php } ?>
        <?php if ($this->view->sucessoCadastro) { ?>
            <small class="center form-text text-success">Cadastro efetuado com sucesso.</small>
        <?php } ?>
        <div class="center">
            <button type="submit" id="realizarCadastro" class="btn btn-sm">Realizar cadastro</button>
        </div>

        <div id="linkColorInfo">
            <a href="/">Voltar para a Página Inicial</a>
        </div>

    </form>


</div>