<div class="mt-5">
    <?php
    print_r($_GET);
    ?>
    <?= $this->view->medico['email'] ?>
    <form method="post" action="editarMedico">
        <h4 id="titulo" class="center">Editar médico</h4>
        <div>
            <strong id="titulo">Nome</strong>
            <input id='formulario' type="text" name="" class="form-control form-control-sm" value="  <?= $this->view->medico['nome']  ?>">
        </div>
        <div class="mt-3">
            <strong id="titulo">Senha antiga</strong>
            <input id='formulario' type="password" class="form-control form-control-sm" placeholder="Escolha uma senha forte e segura">
        </div>
        <div class="mt-3">
            <strong id="titulo">Nova senha</strong>
            <input id='formulario' type="password" class="form-control form-control-sm" placeholder="Escolha uma senha forte e segura">
        </div>
        <div class="center">
            <button id="realizarCadastro" class="btn btn-sm">Atualizar cadastro</button>
        </div>
        <div id="linkColorInfo">
            <a href="/">Voltar para a Página Inicial</a>
        </div>
    </form>
</div>