<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" href="css/style.css">

    <title>
        Fácil Consulta
    </title>
</head>

<body>
    <!doctype html>
    <html lang="en">

    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="public\css\style.css">
        <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Signika" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"> -->
        <title>Fácil Consulta</title>
    </head>

    <body>
        <header id="menu">

            <div class="container">
                <a id="cadastroMedico" href="cadastro_medico" class="btn btn-light mt-4"> Cadastro de médico </a>
            </div>
        </header>
        <div class="container d-flex justify-content-center">
            <?php $this->content() ?>

    </body>

    </html>