
CREATE SCHEMA IF NOT EXISTS `facilconsulta` DEFAULT CHARACTER SET utf8mb4 ;
USE `facilconsulta` ;

CREATE TABLE IF NOT EXISTS `facilconsulta`.`horario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_medico` INT(11) NULL DEFAULT NULL,
  `data_horario` DATETIME NULL DEFAULT NULL,
  `horario_agendado` TINYINT(1) NULL DEFAULT NULL,
  `data_criacao` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
  `data_alteracao` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;
CREATE TABLE IF NOT EXISTS `facilconsulta`.`medico` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `senha` VARCHAR(255) NULL DEFAULT NULL,
  `data_criacao` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
  `data_alteracao` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;